name: Gina Razon Mezzo Soprano
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28392
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151716'
    - '#951744'
    - '#b4917d'
    - '#8d6855'
    - '#dcc9a9'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
