name: Gina Razon Mezzo Soprano
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5780951075721532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#635646'
    - '#eeeeee'
    - '#bb161f'
    - '#ada7ab'
  brandStrength: 0.12800500728189945
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
