name: Gina Razon Mezzo Soprano
favicon: null
layout_spectrum: 0.30707657616585493
typography_spectrum: 0.5780951075721532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12800500728189945
  lightness: 0.8317843568511307
  saturation: 0.8816789579577744
  rhythmicContrast: 0.7045038933865726
purpose: []
